Header bibliothèque
WildCodeSchool/tlse0320-p2-GameHoarder pull request #13
Opened 2020-04-23 07:49 UTC by Waledak

header pour la page bibliothèque, le statut ne se stock pas encore et le composant n'est en encore en lien avec les autres composant concernant la bibliothèque.

2020-04-23 07:52 UTC, LessBeaver submitted a review, later dismissed

2020-04-23 08:01 UTC, BenjaminDexant submitted a review, later dismissed

2020-04-23 08:58 UTC, Froyj requested changes
Dresser issue pour :
- Composant classe inutile dans NewGameCard

2020-04-23 08:58 UTC, Froyj commented on src/App.jsx
> +import GetGames from './components/data/getCardData/GetGames';
pas utilisé ! à enlever

2020-04-23 08:58 UTC, Froyj commented on src/components/contents/MyGames.jsx
>  import Filters from './filter/Filters';
Attention essayer d'être un peu plus précis sur les noms de composant. Filters c'est un peu trop générique

2020-04-23 08:58 UTC, Froyj commented on src/components/contents/my-games/ListMyGameCards.jsx
>          />
Essayer de voir ça ==> https://reactpatterns.com/#container-component
(Voir renommer displayMyGameCard) pas indispensable mais toujours bon à prendre

2020-04-23 08:58 UTC, Froyj commented on src/components/data/getCardData/GetGames.jsx
> +    console.log(this.state.games);
Retirer le console.log

2020-04-23 08:58 UTC, Froyj commented on src/components/header/HeaderLib.jsx
> +  checkIsGameInLibrairy() {
**Library** et pas **Librairy** si vous voulez éviter de vous planter par la suite entre ceux qui l'orthographie correctement et les autres

2020-04-23 08:58 UTC, Froyj commented on src/components/header/HeaderLib.jsx
> +    if (this.state.lastGameName !== null && window.localStorage.lenght > 0) {
window.localStorage.**length** et pas window.localStorage.**lenght**

2020-04-23 08:58 UTC, Froyj commented on src/components/header/HeaderLib.jsx
> +import React from 'react';
Corriger tous les retours en rouge d'eslint

2020-04-23 12:08 UTC, BenjaminDexant submitted a review, later dismissed

2020-04-23 12:15 UTC, LessBeaver submitted a review, later dismissed

2020-04-24 07:48 UTC, LessBeaver submitted a review, later dismissed

2020-04-24 14:29 UTC, LessBeaver approved these changes

2020-04-28 07:48 UTC, LessBeaver approved these changes

2020-04-28 12:37 UTC, Froyj commented on src/components/contents/my-games/NewGameCard.jsx
> +    const { rating } = this.props;
const { name, url, rating } = this.props

2020-04-28 12:40 UTC, Froyj submitted a review, later dismissed

2020-04-28 14:23 UTC, LessBeaver submitted a review, later dismissed

2020-04-28 14:58 UTC, LessBeaver approved these changes

2020-04-28 14:59 UTC, tristan-git approved these changes
ok

2020-04-28 14:59 UTC, merged