Header suggestions
WildCodeSchool/tlse0320-p2-GameHoarder pull request #17
Opened 2020-04-25 16:04 UTC by LessBeaver

Header de la partie "Suggestion" de l'utilisateur, html/css.
Fonctionnalité : possibilitée d'ajouter le jeu en suggestion directement à sa bibliothèque personnelle.

2020-04-27 13:56 UTC, Waledak approved these changes
fait attention à pas tout merge sur ta branch la prochaine fois sinon ok pour moi (du moins pour ce qui est de ta partie)

2020-04-28 13:29 UTC, Waledak requested changes
have some change

2020-04-28 13:29 UTC, Waledak commented on src/App.jsx
> +// import GetGames from './components/data/getCardData/GetCardData';
pas de code mort

2020-04-28 13:29 UTC, Waledak commented on src/components/contents/my-games/MyGameCard.jsx
> +/* eslint-disable no-useless-constructor */
pas de code mort

2020-04-28 13:29 UTC, Waledak commented on src/components/contents/my-games/NewGameCard.jsx
> +/* eslint-disable no-useless-constructor */
code mort

2020-04-28 13:29 UTC, Waledak commented on src/components/contents/my-games/NewGameCard.jsx
>      const { url } = this.props;
réunir name et url pour la destructuration

2020-04-28 13:41 UTC, Waledak approved these changes
ok pour moi

2020-04-28 13:42 UTC, tristan-git approved these changes
ok ( le header lib.jsx sera review pendant la PR de Tanguy )

2020-04-28 13:43 UTC, merged