sprint 1
WildCodeSchool/tlse0320-p2-GameHoarder pull request #2
Opened 2020-04-17 09:57 UTC by tristan-git

possibilité d'ajouter un jeux depuis la liste de jeux "New Game" en cliquant sur le bouton "ajouter un jeux"
possibilité de supprimer un jeux de la bibliotheque en cliquant sur le bouton "poubelle"
la liste de jeux de la bibliotheque est sauvegardée localement. (local storage)
possibilté de rechercher un jeux seulement dans la partie "New Game" pour l'instant à l'aide de la barre de recherche

2020-04-20 10:08 UTC, Froyj requested changes
Resoumettre la PR en enlevant les fichiers superflus (package-lock.json)

2020-04-20 10:08 UTC, Froyj commented on .eslintrc.json
> +    // "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
Enlever ça

2020-04-20 10:08 UTC, Froyj commented on .vscode/settings.json
> +  "git.ignoreLimitWarning": true
Ca sert à quoi ? pourquoi le mettre ?

2020-04-20 10:08 UTC, Froyj commented on gameHoarder.code-workspace
> +}
ne mettez pas le fichier du workspace dans le repo

2020-04-20 10:08 UTC, Froyj commented on src/components/data/getCardData/GetCardData.jsx
> +      </div>
Requête API ne fonctionne pas chez moi

2020-04-20 10:08 UTC, Froyj commented on src/components/header/Header.jsx
> +// Header.propTypes = {};
Code mort : on enlève

2020-04-20 10:08 UTC, Froyj commented on src/components/mobile-nav/MobileNav.jsx
> +// import PropTypes from 'prop-types';
code mort

2020-04-20 10:08 UTC, Froyj commented on src/components/mobile-nav/MobileNav.jsx
> +// MobileNav.propTypes = {};
code mort

2020-04-20 10:08 UTC, Froyj commented on src/components/footer/Footer.jsx
> +// import PropTypes from 'prop-types';
code mort

2020-04-22 07:19 UTC, Waledak commented on src/components/data/getCardData/GetCardData.jsx
> +      </div>
oui on sait, on a un problème de CORS qu'on arrive pas à résoudre, même avec des extensions

2020-04-22 11:49 UTC, Froyj commented on src/components/data/getCardData/GetCardData.jsx
> +      </div>
alors la ca fonctionne maintenant. A surveiller !

2020-04-22 11:57 UTC, Froyj commented
Attention au nom des commits suite aux changements demandés. Groupes tes commits en indiquant clairement à quels changements les commits répondent. 
Exemple : "removed dead code"

Ces 2 là sont bien par exemple :
@Waledak
Delete package-lock.json
911660c
@Waledak
Delete gameHoarder.code-workspace

RULE#1 Faire des commits atomiques

2020-04-22 11:57 UTC, Froyj approved these changes

2020-04-22 11:58 UTC, Froyj requested changes
Attention la page ne se met pas à jour automatiquement quand on ajoute des jeux ==> voir du coté de ComponentDidUpdate

2020-04-22 12:40 UTC, Froyj approved these changes

2020-04-22 15:20 UTC, Waledak approved these changes

2020-04-22 15:20 UTC, merged